spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

logging:
  level:
    com.skillmatch: INFO
    com.skillmatch.backend.security: DEBUG

skillmatch:
  hh-import:
    enabled: true

app:
  jwt:
    secret: ${JWT_SECRET}
    accessTokenTtlMinutes: 120
  verification:
    codeTtlMinutes: 10
  oauth:
    google:
      clientId: ${GOOGLE_CLIENT_ID}
      clientsecret: ${GOOGLE_CLIENT_SECRET}
    yandex:
      clientId: ${YANDEX_CLIENT_ID}
      clientSecret: ${YANDEX_CLIENT_SECRET}
      redirectUri: ${YANDEX_REDIRECT_URI}
  management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: never