import {Dimensions, StyleSheet} from 'react-native';

export const gStyle = StyleSheet.create({
    main: {
        flex: 1,
    },
    title: {
        fontSize: 18,
    },
});

export const headStyle = StyleSheet.create({
    background: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    logo:{
        width: '60%',
        height: '60%',
        aspectRatio: 1,
    },
    buttonContainer: {
        marginTop: 20,
    },
    button: {
        backgroundColor: 'rgba(24, 11, 80, 0.5)', // тот самый #180B5066 💜
        paddingVertical: '5%',
        paddingHorizontal: '15%',
        borderRadius: 25,
        alignItems: 'center',
    },
    buttonText: {
        color: '#FFFFFF', // белый текст, НЕ прозрачный
        fontSize: 16,
        fontWeight: 'bold',
    },
    backButton: {
        position: 'absolute',
        top: 50,
        left: 20,
        zIndex: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        borderRadius: 25,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    backButtonText: {
        color: '#ffffff',
        fontSize: 24,
        fontWeight: 'bold',
    },
});

export const stylesRedirect = StyleSheet.create({
    container: {
        flex: 1,
    },
    background: {
        flex: 1,
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 20,
        top: '5%',
        color: '#ffffff',
    },
    subtitle: {
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 30,
        color: '#ffffff',
        opacity: 0.9,
        top: '10%',
    },
    buttonsContainer: {
        width: '100%',
        alignItems: 'center',
        gap: 15,
        top: '8%',
    },
    button: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 50,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#ddd',
    },
    manualButton: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 15,
        paddingHorizontal: 20,
        borderRadius: 50,
        backgroundColor: '#6B46C1',
    },
    iconPlaceholder: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#ccc',
        marginRight: 15,
    },
    buttonText: {
        fontSize: 16,
        color: '#000',
    },
    manualButtonText: {
        fontSize: 16,
        color: '#fff',
        flexShrink: 1,
    },
    backButton: {
        position: 'absolute',
        top: 50,
        left: 20,
        zIndex: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        borderRadius: 25,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    backButtonText: {
        color: '#ffffff',
        fontSize: 24,
        fontWeight: 'bold',
    },
});

export const stylesRegister = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    background: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 30,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 30,
        color: '#4131B6',
    },
    formContainer: {
        width: '100%',
    },
    inputGroup: {
        marginBottom: 15,
    },
    label: {
        fontSize: 14,
        color: '#666666',
        marginBottom: 8,
    },
    input: {
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        color: '#000000',
        width: '100%',
    },
    inputError: {
        borderWidth: 1,
        borderColor: '#FF0000',
    },
    errorText: {
        color: '#FF0000',
        fontSize: 12,
        marginTop: 4,
        marginLeft: 4,
    },
    dateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8E4FF',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        width: '100%',
    },
    dateButtonText: {
        fontSize: 16,
        color: '#4131B6',
        marginLeft: 12,
        flex: 1,
    },
    resumeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8E4FF',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        width: '100%',
    },
    resumeButtonText: {
        fontSize: 16,
        color: '#4131B6',
        marginLeft: 12,
        flex: 1,
    },
    continueButton: {
        backgroundColor: '#4131B6',
        borderRadius: 50,
        paddingVertical: 16,
        paddingHorizontal: 24,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 30,
        width: '100%',
    },
    continueButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
        marginRight: 8,
    },
    iconContainer: {
        width: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
    },
    backButton: {
        position: 'absolute',
        top: 60,
        left: 20,
        zIndex: 10,
        backgroundColor: 'rgba(65, 49, 182, 0.1)',
        borderRadius: 25,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    backButtonText: {
        color: '#4131B6',
        fontSize: 24,
        fontWeight: 'bold',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 40,
        maxHeight: '70%',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#000000',
        marginBottom: 20,
        textAlign: 'center',
    },
    dateSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 20,
        paddingHorizontal: 10,
    },
    arrowButton: {
        fontSize: 24,
        color: '#4131B6',
        fontWeight: 'bold',
        paddingHorizontal: 15,
    },
    dateDisplay: {
        alignItems: 'center',
        flex: 1,
    },
    yearText: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#4131B6',
        marginBottom: 4,
    },
    monthText: {
        fontSize: 18,
        color: '#4131B6',
    },
    calendarContainer: {
        marginBottom: 20,
    },
    calendarGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
    },
    calendarDay: {
        width: '14.28%',
        aspectRatio: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    calendarDayEmpty: {
        opacity: 0,
    },
    calendarDaySelected: {
        backgroundColor: '#4131B6',
        borderRadius: 20,
    },
    calendarDayText: {
        fontSize: 16,
        color: '#000000',
    },
    calendarDayTextSelected: {
        color: '#FFFFFF',
        fontWeight: 'bold',
    },
    saveButton: {
        backgroundColor: '#4131B6',
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 24,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
})

export const stylesVerification = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    background: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 30,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 30,
        color: '#4131B6',
        marginTop: 50
    },
    backButton: {
        position: 'absolute',
        top: 60,
        left: 20,
        zIndex: 10,
        backgroundColor: 'rgba(65, 49, 182, 0.1)',
        borderRadius: 25,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    backButtonText: {
        color: '#4131B6',
        fontSize: 24,
        fontWeight: 'bold',
    },
    inputGroup: {
        marginBottom: 15,
    },
    label: {
        fontSize: 14,
        color: '#666666',
        marginLeft: '10%',
        marginBottom: '2%',
    },
    input: {
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        color: '#000000',
        width: '80%',
        margin: 'auto',
    },
    resendButton: {
        backgroundColor: '#4131B6',
        borderRadius: 50,
        paddingVertical: 16,
        paddingHorizontal: 24,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        width: '80%',
        margin: 'auto',
    },
    resendButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
        marginRight: 8,
    },
})

export const stylesPassword = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    background: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 30,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 30,
        color: '#4131B6',
        marginTop: 50
    },
    backButton: {
        position: 'absolute',
        top: 60,
        left: 20,
        zIndex: 10,
        backgroundColor: 'rgba(65, 49, 182, 0.1)',
        borderRadius: 25,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    backButtonText: {
        color: '#4131B6',
        fontSize: 24,
        fontWeight: 'bold',
    },
    inputGroup: {
        marginBottom: 15,
    },
    label: {
        fontSize: 14,
        color: '#666666',
        marginLeft: '10%',
        marginBottom: '2%',
    },
    input: {
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        color: '#000000',
        width: '80%',
        margin: 'auto',
    },
    inputError: {
        borderWidth: 1,
        borderColor: '#FF3B30',
    },
    errorText: {
        color: '#FF3B30',
        fontSize: 12,
        marginTop: 5,
        marginLeft: '10%',
    },
    continueButton: {
        backgroundColor: '#4131B6',
        borderRadius: 50,
        paddingVertical: 16,
        paddingHorizontal: 24,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: '90%',
        width: '80%',
        margin: 'auto',
    },
    continueButtonDisabled: {
        backgroundColor: '#CCCCCC',
        opacity: 0.6,
    },
    continueButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
        marginRight: 8,
    },
})

export const stylesSkillsChoose = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    background: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 10,
        position: 'relative',
    },
    continueButton: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 50,
        paddingVertical: 12,
        paddingHorizontal: 20,
        position: 'absolute',
        right: 20,
        top: 60,
        zIndex: 10,
    },
    continueButtonText: {
        color: '#4131B6',
        fontSize: 16,
        fontWeight: 'bold',
        marginRight: 8,
    },
    continueButtonArrow: {
        color: '#FFFFFF',
        fontSize: 16,
    },
    scrollContent: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 30,
    },
    backButton: {
        position: 'absolute',
        top: 60,
        left: 20,
        zIndex: 10,
        backgroundColor: 'rgba(65, 49, 182, 0.1)',
        borderRadius: 25,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    backButtonText: {
        color: '#4131B6',
        fontSize: 24,
        fontWeight: 'bold',
    },
    title: {
        color: '#000000',
        fontSize: 27,
        fontWeight: 'bold',
        marginLeft: '7%',
        marginTop: '5%',
        marginBottom: 10,
    },
    description: {
        color: '#000000',
        fontSize: 14,
        marginLeft: '7%',
        marginBottom: 30,
        fontWeight: '300',
    },
    customSkillSection: {
        marginLeft: '7%',
        marginRight: '7%',
        marginBottom: 30,
    },
    customSkillTitle: {
        color: '#000000',
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 12,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    searchInput: {
        flex: 1,
        fontSize: 14,
        color: '#000000',
        paddingRight: 10,
    },
    searchIcon: {
        fontSize: 20,
        color: '#4131B6',
    },
    skillsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        paddingHorizontal: '7%',
        gap: 12,
    },
    skillButton: {
        width: '47%',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#4131B6',
        paddingVertical: 16,
        paddingHorizontal: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        marginBottom: 12,
    },
    skillButtonSelected: {
        backgroundColor: '#4131B6',
        borderColor: '#4131B6',
    },
    skillIconSelected: {
        color: '#FFFFFF',
    },
    skillText: {
        fontSize: 16,
        color: '#4131B6',
        fontWeight: '500',
    },
    skillTextSelected: {
        color: '#FFFFFF',
    },
})

export const stylesExpectations = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    background: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 10,
        position: 'relative',
    },
    continueButton: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 50,
        paddingVertical: 12,
        paddingHorizontal: 20,
        position: 'absolute',
        right: 20,
        top: 60,
        zIndex: 10,
    },
    continueButtonText: {
        color: '#4131B6',
        fontSize: 16,
        fontWeight: 'bold',
        marginRight: 8,
    },
    continueButtonArrow: {
        color: '#FFFFFF',
        fontSize: 16,
    },
    scrollContent: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 200,
    },
    backButton: {
        position: 'absolute',
        top: 60,
        left: 20,
        zIndex: 10,
        backgroundColor: 'rgba(65, 49, 182, 0.1)',
        borderRadius: 25,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    backButtonText: {
        color: '#4131B6',
        fontSize: 24,
        fontWeight: 'bold',
    },
    title: {
        color: '#000000',
        fontSize: 27,
        fontWeight: 'bold',
        marginLeft: '7%',
        marginTop: '5%',
        marginBottom: 10,
    },
    description: {
        color: '#000000',
        fontSize: 14,
        marginLeft: '7%',
        marginBottom: 30,
        fontWeight: '300',
    },
    section: {
        marginLeft: '7%',
        marginRight: '7%',
        marginBottom: 30,
        overflow: 'visible',
    },
    sectionTitle: {
        color: '#000000',
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 15,
    },
    formatsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        borderRadius: 30,
        padding: 12,
        gap: 10,
        borderWidth: 1,
        borderColor: 'lightgrey',
    },
    formatButton: {
        width: '47%',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
        borderColor: 'lightgrey',
        boxShadow: '2px 2px 5px grey',
    },
    formatButtonSelected: {
        backgroundColor: '#4131B6',
    },
    formatText: {
        fontSize: 14,
        color: '#000000',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    formatTextSelected: {
        color: '#FFFFFF',
    },
    salaryContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderRadius: 30,
        borderWidth: 1,
        borderColor: 'lightgrey',
        padding: 12,
        gap: 10,
        overflow: 'visible',
    },
    salaryInputWrapper: {
        flex: 1,
    },
    periodWrapper: {
        flex: 1,
        overflow: 'visible',
    },
    periodContainer: {
        position: 'relative',
        zIndex: 1000,
        overflow: 'visible',
    },
    salaryLabel: {
        fontSize: 14,
        color: 'black',
        marginBottom: 8,
        fontWeight: 'bold',
    },
    inputSalary: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        paddingVertical: 14,
        paddingHorizontal: 16,
        fontSize: 16,
        color: '#000000',
    },
    periodButton: {
        borderWidth: 1,
        borderColor: 'lightgrey',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    periodButtonText: {
        color: '#999999',
        fontSize: 16,
    },
    periodButtonTextSelected: {
        color: '#000000',
    },
    periodButtonArrow: {
        color: '#FFFFFF',
        fontSize: 12,
        marginLeft: 8,
    },
    periodDropdown: {
        position: 'absolute',
        top: '100%',
        left: 0,
        right: 0,
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderTopWidth: 0,
        marginTop: 0,
        overflow: 'hidden',
        zIndex: 10000,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 10,
        maxHeight: 200,
    },
    periodDropdownScroll: {
        maxHeight: 200,
    },
    periodOption: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    periodOptionLast: {
        borderBottomWidth: 0,
    },
    periodOptionSelected: {
        backgroundColor: '#4131B6',
    },
    periodOptionText: {
        fontSize: 16,
        color: '#000000',
    },
    periodOptionTextSelected: {
        color: '#FFFFFF',
        fontWeight: 'bold',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'transparent',
    },
    periodDropdownModal: {
        position: 'absolute',
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderTopWidth: 0,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 10,
    },
})